# markdownlint config

# The CHANGELOG contains duplicated headers by design
MD024: false

# MD013/line-length: disable line length for all. We prefer lines as
# long as paragraph with in-editor line breaks.
MD013: false

# MD048/code-fence-style: code fence style
MD048:
  style: backtick
