# vim: ft=yaml

name: test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3
  BUNDLE_WITHOUT: development

jobs:
  rspec:
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
        gemfile:
          - rails_8.0
          - rails_7.2
          - rails_7.1
          - rails_7.0
          - rails_6.1
        exclude:
          - ruby: "3.4"
            gemfile: rails_7.0
          - ruby: "3.4"
            gemfile: rails_6.1
          - ruby: "3.1"
            gemfile: rails_8.0
      fail-fast: False

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt-get install --quiet --yes libsqlite3-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: True

      - run: bundle exec rspec --color --format documentation

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: True

      - run: bundle exec rubocop --parallel --color
